[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Services.RelativityScriptRunner.#ExecuteJobInWorkspace(kCura.Relativity.Client.IRSAPIClient,Milyli.ScriptRunner.Core.Models.JobSchedule)", Justification = "Inline format")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Services.RelativityScriptRunner.#ExecuteScriptJob(Milyli.ScriptRunner.Core.Models.JobSchedule)", Justification = "Inline format")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Services.RelativityScriptRunner.#ExecuteAllJobs(System.DateTime)", Justification = "Inline format")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Repositories.JobScheduleRepository.#StartJob(Milyli.ScriptRunner.Core.Models.JobSchedule)", Justification = "Inline format")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Repositories.JobScheduleRepository.#LockJobSchedule(Milyli.ScriptRunner.Core.Models.JobSchedule,LinqToDB.Data.DataConnectionTransaction)", Justification = "Inline format")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Repositories.JobScheduleRepository.#FinishJob(Milyli.ScriptRunner.Core.Models.JobSchedule)", Justification = "Inline format")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Milyli.ScriptRunner.Core.Repositories.JobScheduleRepository.#ActivateJob(Milyli.ScriptRunner.Core.Models.JobSchedule)", Justification = "Inline format")]

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
