//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milyli.ScriptRunner.EventHandlers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Milyli.ScriptRunner.EventHandlers.SqlScript", typeof(SqlScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;JobHistory&apos;, &apos;u&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE JobHistory
        ///	(
        ///		JobHistoryId int not null IDENTITY(1,1),
        ///		JobScheduleId int not null,
        ///		StartTime DATETIME not null,
        ///		Runtime INT null,
        ///		Errored BIT NOT NULL,
        ///		ResultText NVARCHAR(max),
        ///		CONSTRAINT PK_JobHistory_JobHistoryId PRIMARY KEY CLUSTERED (JobHistoryId),
        ///		CONSTRAINT FK_JobHistory_JobSchedule FOREIGN KEY (JobScheduleId) REFERENCES JobSchedule(JobScheduleId)
        ///	)
        ///
        ///	CREATE INDEX IX_JobHistory_ByScheduleStart ON JobHistory (JobScheduleId, S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobHistory_Table {
            get {
                return ResourceManager.GetString("JobHistory_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;JobSchedule&apos;, &apos;u&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE JobSchedule (
        ///		JobScheduleId int not null IDENTITY(1,1),
        ///		RelativityScriptId INT NOT NULL,
        ///		WorkspaceId INT NOT NULL,
        ///		JobName nvarchar(255) NULL,
        ///		LastExecutionTime DATETIME NULL,
        ///		NextExecutionTime DATETIME NULL,
        ///		JobStatus INT not null,
        ///		JobEnabled BIT NOT NULL,
        ///		MaximumRuntime int NOT NULL,
        ///		ExecutionTime INT NOT NULL,
        ///		ExecutionSchedule INT NOT NULL,
        ///		CONSTRAINT PK_JobSchedule_JobScheduleId PRIMARY KEY CLUSTERED (JobScheduleId)
        ///	) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobSchedule_Table {
            get {
                return ResourceManager.GetString("JobSchedule_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;JobScriptInput&apos;, &apos;u&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE JobScriptInput
        ///	(
        ///		JobScriptInputId int not null IDENTITY(1,1),
        ///		JobScheduleId int not null,
        ///		InputId nvarchar(255) not null,
        ///		InputName nvarchar(255) not null,
        ///		InputValue nvarchar(max),
        ///		CONSTRAINT PK_JobScriptInput_JobScriptInputId PRIMARY KEY CLUSTERED (JobScriptInputId),
        ///		CONSTRAINT FK_JobScriptInput_JobSchedule FOREIGN KEY (JobScheduleId) REFERENCES JobSchedule(JobScheduleId)
        ///	)
        ///
        ///	CREATE INDEX IX_JobScriptInput_JobScheduleId ON Job [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobScriptInput_Table {
            get {
                return ResourceManager.GetString("JobScriptInput_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;JobSchedule&apos;, &apos;u&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE JobSchedule (
        ///		JobScheduleId int not null IDENTITY(1,1),
        ///		RelativityScriptId INT NOT NULL,
        ///		WorkspaceId INT NOT NULL,
        ///		JobName nvarchar(255) NULL,
        ///		LastExecutionTime DATETIME NULL,
        ///		NextExecutionTime DATETIME NULL,
        ///		JobStatus INT not null,
        ///		JobEnabled BIT NOT NULL,
        ///		MaximumRuntime int NOT NULL,
        ///		ExecutionTime INT NOT NULL,
        ///		ExecutionSchedule INT NOT NULL,
        ///		CONSTRAINT PK_JobSchedule_JobScheduleId PRIMARY KEY CLUSTERED (JobScheduleId)
        ///	) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptRunnerSchema {
            get {
                return ResourceManager.GetString("ScriptRunnerSchema", resourceCulture);
            }
        }
    }
}
